apiVersion: v1
kind: Service
metadata:
  name: pgadmin4
  namespace: d2wpgadmin
spec:
  ports:
    - name: tcp
      protocol: TCP
      port: 5050
      targetPort: 5050
  selector:
    app: pgadmin4
  type: ClusterIP
  sessionAffinity: None