apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin4
  namespace: d2wpgadmin
  labels:
    app: pgadmin4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin4
  template:
    metadata:
      labels:
        app: pgadmin4
    spec:
      containers:
      - name: pgadmin4
        image: skfxz98aacr.azurecr.io/pgadmin4:latest
        ports:
          - containerPort: 5050
        env:
          - name: PGADMIN_DEFAULT_EMAIL
            value: 'andrea.carpene@skf.com'
          - name: PGADMIN_DEFAULT_PASSWORD
            value: 'Latina,1!'